name: Greenemusic
favicon: null
layout_spectrum: 1
typography_spectrum: 1
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Ron Greene music official website
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0C0C0E'
    - '#91ACCF'
    - '#777888'
    - '#F0F1F3'
    - '#855143'
  brandStrength: 0.7771545
  lightness: 0.3234043
  saturation: 0.4574468
  rhythmicContrast: 0.6744681
purpose: []
