layout_spectrum: 0.3948921
typography_spectrum: 1
color:
  saturation: 0.1311974
  brandStrength: 0.7771545
  lightness: 0.9453949
  brandColors:
    - '#0C0C0E'
    - '#91ACCF'
    - '#777888'
    - '#F0F1F3'
    - '#855143'
  rhythmicContrast: 0.6578813
name: Greenemusic
